"""inicial creo

Revision ID: 116f494598e4
Revises: 
Create Date: 2024-04-24 15:50:43.918706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116f494598e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Obtener la conexión a la base de datos
    connection = op.get_bind()

    # Verificar si la tabla 'usuario' existe
    if connection.dialect.has_table(connection, 'usuario'):
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('usuario')
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(
                        length=50), nullable=False),
                    sa.Column('password', sa.VARCHAR(
                        length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###
