"""agregando campos de created_at y by a client

Revision ID: 4ba8e71fb398
Revises: 116f494598e4
Create Date: 2024-04-24 16:53:49.303985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba8e71fb398'
down_revision = '116f494598e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:

        inspector = sa.inspect(op.get_bind())
        columns = inspector.get_columns('client')

        created_at_exists = any(
            column['name'] == 'created_at' for column in columns)
        created_by_type_exists = any(
            column['name'] == 'created_by_type' for column in columns)
        created_by_exists = any(
            column['name'] == 'created_by' for column in columns)

        if not created_at_exists:
            batch_op.add_column(
                sa.Column('created_by', sa.String(length=50), nullable=False))
        if not created_by_type_exists:
            batch_op.add_column(sa.Column('created_by_type',
                                          sa.String(length=50), nullable=False))
        if not created_by_exists:
            batch_op.add_column(
                sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:

        inspector = sa.inspect(op.get_bind())
        columns = inspector.get_columns('client')

        created_at_exists = any(
            column['name'] == 'created_at' for column in columns)
        created_by_type_exists = any(
            column['name'] == 'created_by_type' for column in columns)
        created_by_exists = any(
            column['name'] == 'created_by' for column in columns)

        if created_at_exists:
            batch_op.drop_column('created_at')
        if created_by_type_exists:
            batch_op.drop_column('created_by_type')
        if created_by_exists:
            batch_op.drop_column('created_by')

    # ### end Alembic commands ###
