"""agregando campos de created_at y by a client

Revision ID: 4ba8e71fb398
Revises: 116f494598e4
Create Date: 2024-04-24 16:53:49.303985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba8e71fb398'
down_revision = '116f494598e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_by_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by_type')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
