"""removing doc_type

Revision ID: d37cf31ef026
Revises: d699c8283c92
Create Date: 2024-04-25 10:40:52.441482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37cf31ef026'
down_revision = 'd699c8283c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('doc_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
