"""added odoo_client_id field to Client model

Revision ID: d699c8283c92
Revises: 5dce4981227e
Create Date: 2024-04-25 08:55:26.134116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd699c8283c92'
down_revision = '5dce4981227e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odoo_client_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint("unique_odoo_client_id", ['odoo_client_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('odoo_client_id')

    # ### end Alembic commands ###
